### ISSUE TITLE
Only plays one song then stops - Chrome

### ISSUE THREAD

**Issue by Designer-Drums** [pvrs12/Anesidora#33]
Looks like this issue has reappeared. Please fix. :) Thanks!

**Comment by seveerekaj** [comment]
Yep. Same issue as #5. I'm also seeing the same thing with the Android FF version, but the desktop FF version seems to be working fine. In all cases, I tested using the latest version, 1.12.1

**Comment by pvrs12** [comment]
Thanks both for the report. I'll dig into this tonight..

I had forgotten last night that I was releasing an older version for Chrome due to this bug (I really should have tagged/branched that..)

**Comment by pvrs12** [comment]
I've made a change which I hope should fix this.

I believe it was related to using `browser` instead of `chrome` in the chrome version. Firefox can handle either, but chrome is picky. I've added that to the platform specific file so I can get the right variable for the browser which is being used

**Comment by seveerekaj** [comment]
Chrome is now working properly. Still seeing the same behavior on Android FF though - should I open a separate issue for that?

**Comment by pvrs12** [comment]
I think that the most recent 2 commits should fix the Android issue. I've published it to the mozilla store as 1.12.3 (and releases page).

**Comment by seveerekaj** [comment]
Hooray, it's fixed! Thanks again for all your great work on this.

**Comment by pvrs12** [comment]
Woo! Thanks for always testing it so quickly!
